package com.animalmanagement.mapper;

import com.animalmanagement.entity.AdminToken;
import com.animalmanagement.example.AdminTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AdminTokenMapper {
    long countByExample(AdminTokenExample example);

    int deleteByExample(AdminTokenExample example);

    int deleteByPrimaryKey(Integer token);

    int insert(AdminToken record);

    int insertSelective(AdminToken record);

    List<AdminToken> selectByExampleWithRowbounds(AdminTokenExample example, RowBounds rowBounds);

    List<AdminToken> selectByExample(AdminTokenExample example);

    AdminToken selectByPrimaryKey(Integer token);

    int updateByExampleSelective(@Param("record") AdminToken record, @Param("example") AdminTokenExample example);

    int updateByExample(@Param("record") AdminToken record, @Param("example") AdminTokenExample example);

    int updateByPrimaryKeySelective(AdminToken record);

    int updateByPrimaryKey(AdminToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admintoken
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AdminToken selectOneByExample(AdminTokenExample example);
}