package com.animalmanagement.mapper;

import com.animalmanagement.entity.Adoption;
import com.animalmanagement.example.AdoptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AdoptionMapper {
    long countByExample(AdoptionExample example);

    int deleteByExample(AdoptionExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(Adoption record);

    int insertSelective(Adoption record);

    List<Adoption> selectByExampleWithRowbounds(AdoptionExample example, RowBounds rowBounds);

    List<Adoption> selectByExample(AdoptionExample example);

    Adoption selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") Adoption record, @Param("example") AdoptionExample example);

    int updateByExample(@Param("record") Adoption record, @Param("example") AdoptionExample example);

    int updateByPrimaryKeySelective(Adoption record);

    int updateByPrimaryKey(Adoption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adoption
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Adoption selectOneByExample(AdoptionExample example);
}