package com.animalmanagement.mapper;

import com.animalmanagement.entity.Animal;
import com.animalmanagement.example.AnimalExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

@Mapper
public interface AnimalMapper {
    long countByExample(AnimalExample example);

    int deleteByExample(AnimalExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(Animal record);

    int insertSelective(Animal record);

    List<Animal> selectByExampleWithRowbounds(AnimalExample example, RowBounds rowBounds);

    List<Animal> selectByExample(AnimalExample example);

    Animal selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") Animal record, @Param("example") AnimalExample example);

    int updateByExample(@Param("record") Animal record, @Param("example") AnimalExample example);

    int updateByPrimaryKeySelective(Animal record);

    int updateByPrimaryKey(Animal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Animal selectOneByExample(AnimalExample example);
}