package com.animalmanagement.mapper;

import com.animalmanagement.entity.CommentLikeKey;
import com.animalmanagement.example.CommentLikeExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface CommentLikeMapper {
    long countByExample(CommentLikeExample example);

    int deleteByExample(CommentLikeExample example);

    int deleteByPrimaryKey(CommentLikeKey key);

    int insert(CommentLikeKey record);

    int insertSelective(CommentLikeKey record);

    List<CommentLikeKey> selectByExampleWithRowbounds(CommentLikeExample example, RowBounds rowBounds);

    List<CommentLikeKey> selectByExample(CommentLikeExample example);

    int updateByExampleSelective(@Param("record") CommentLikeKey record, @Param("example") CommentLikeExample example);

    int updateByExample(@Param("record") CommentLikeKey record, @Param("example") CommentLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentlike
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CommentLikeKey selectOneByExample(CommentLikeExample example);
}