package com.animalmanagement.mapper;

import com.animalmanagement.entity.StarKey;
import com.animalmanagement.example.StarExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface StarMapper {
    long countByExample(StarExample example);

    int deleteByExample(StarExample example);

    int deleteByPrimaryKey(StarKey key);

    int insert(StarKey record);

    int insertSelective(StarKey record);

    List<StarKey> selectByExampleWithRowbounds(StarExample example, RowBounds rowBounds);

    List<StarKey> selectByExample(StarExample example);

    int updateByExampleSelective(@Param("record") StarKey record, @Param("example") StarExample example);

    int updateByExample(@Param("record") StarKey record, @Param("example") StarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    StarKey selectOneByExample(StarExample example);
}