package com.animalmanagement.mapper;

import com.animalmanagement.entity.Token;
import com.animalmanagement.example.TokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TokenMapper {
    long countByExample(TokenExample example);

    int deleteByExample(TokenExample example);

    int deleteByPrimaryKey(Integer token);

    int insert(Token record);

    int insertSelective(Token record);

    List<Token> selectByExampleWithRowbounds(TokenExample example, RowBounds rowBounds);

    List<Token> selectByExample(TokenExample example);

    Token selectByPrimaryKey(Integer token);

    int updateByExampleSelective(@Param("record") Token record, @Param("example") TokenExample example);

    int updateByExample(@Param("record") Token record, @Param("example") TokenExample example);

    int updateByPrimaryKeySelective(Token record);

    int updateByPrimaryKey(Token record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Token selectOneByExample(TokenExample example);
}