package com.animalmanagement.mapper;

import com.animalmanagement.entity.Track;
import com.animalmanagement.example.TrackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TrackMapper {
    long countByExample(TrackExample example);

    int deleteByExample(TrackExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(Track record);

    int insertSelective(Track record);

    List<Track> selectByExampleWithRowbounds(TrackExample example, RowBounds rowBounds);

    List<Track> selectByExample(TrackExample example);

    Track selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") Track record, @Param("example") TrackExample example);

    int updateByExample(@Param("record") Track record, @Param("example") TrackExample example);

    int updateByPrimaryKeySelective(Track record);

    int updateByPrimaryKey(Track record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table track
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Track selectOneByExample(TrackExample example);
}