package com.animalmanagement.mapper;

import com.animalmanagement.entity.TweetStarKey;
import com.animalmanagement.example.TweetStarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TweetStarMapper {
    long countByExample(TweetStarExample example);

    int deleteByExample(TweetStarExample example);

    int deleteByPrimaryKey(TweetStarKey key);

    int insert(TweetStarKey record);

    int insertSelective(TweetStarKey record);

    List<TweetStarKey> selectByExampleWithRowbounds(TweetStarExample example, RowBounds rowBounds);

    List<TweetStarKey> selectByExample(TweetStarExample example);

    int updateByExampleSelective(@Param("record") TweetStarKey record, @Param("example") TweetStarExample example);

    int updateByExample(@Param("record") TweetStarKey record, @Param("example") TweetStarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweetstar
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TweetStarKey selectOneByExample(TweetStarExample example);
}