package com.animalmanagement.mapper;

import com.animalmanagement.entity.TweetTagKey;
import com.animalmanagement.example.TweetTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TweetTagMapper {
    long countByExample(TweetTagExample example);

    int deleteByExample(TweetTagExample example);

    int deleteByPrimaryKey(TweetTagKey key);

    int insert(TweetTagKey record);

    int insertSelective(TweetTagKey record);

    List<TweetTagKey> selectByExampleWithRowbounds(TweetTagExample example, RowBounds rowBounds);

    List<TweetTagKey> selectByExample(TweetTagExample example);

    int updateByExampleSelective(@Param("record") TweetTagKey record, @Param("example") TweetTagExample example);

    int updateByExample(@Param("record") TweetTagKey record, @Param("example") TweetTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweettag
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TweetTagKey selectOneByExample(TweetTagExample example);
}