package com.animalmanagement.mapper;

import com.animalmanagement.entity.Tweet;
import com.animalmanagement.example.TweetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TweetMapper {
    long countByExample(TweetExample example);

    int deleteByExample(TweetExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(Tweet record);

    int insertSelective(Tweet record);

    List<Tweet> selectByExampleWithBLOBsWithRowbounds(TweetExample example, RowBounds rowBounds);

    List<Tweet> selectByExampleWithBLOBs(TweetExample example);

    List<Tweet> selectByExampleWithRowbounds(TweetExample example, RowBounds rowBounds);

    List<Tweet> selectByExample(TweetExample example);

    Tweet selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") Tweet record, @Param("example") TweetExample example);

    int updateByExampleWithBLOBs(@Param("record") Tweet record, @Param("example") TweetExample example);

    int updateByExample(@Param("record") Tweet record, @Param("example") TweetExample example);

    int updateByPrimaryKeySelective(Tweet record);

    int updateByPrimaryKeyWithBLOBs(Tweet record);

    int updateByPrimaryKey(Tweet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweet
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Tweet selectOneByExample(TweetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweet
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Tweet selectOneByExampleWithBLOBs(TweetExample example);
}