package com.animalmanagement.mapper;

import com.animalmanagement.entity.Verification;
import com.animalmanagement.example.VerificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VerificationMapper {
    long countByExample(VerificationExample example);

    int deleteByExample(VerificationExample example);

    int deleteByPrimaryKey(String email);

    int insert(Verification record);

    int insertSelective(Verification record);

    List<Verification> selectByExampleWithRowbounds(VerificationExample example, RowBounds rowBounds);

    List<Verification> selectByExample(VerificationExample example);

    Verification selectByPrimaryKey(String email);

    int updateByExampleSelective(@Param("record") Verification record, @Param("example") VerificationExample example);

    int updateByExample(@Param("record") Verification record, @Param("example") VerificationExample example);

    int updateByPrimaryKeySelective(Verification record);

    int updateByPrimaryKey(Verification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Verification selectOneByExample(VerificationExample example);
}